--Switch Activity

CREATE TABLE ADDRESS_COMMON(NAME VARCHAR(20),ADDRESS VARCHAR(20),
MAILCODE VARCHAR(5), CITY VARCHAR(20), COUNTRY VARCHAR(20))

CREATE TABLE ADDRESS_INDIA(NAME VARCHAR(20),ADDRESS VARCHAR(20),
 CITY VARCHAR(20), COUNTRY VARCHAR(20))

CREATE TABLE ADDRESS_USA(NAME VARCHAR(20),ADDRESS VARCHAR(20),
 MAILCODE VARCHAR(5), CITY VARCHAR(20), COUNTRY VARCHAR(20))

CREATE TABLE ADDRESS_OTHERS(NAME VARCHAR(20),ADDRESS VARCHAR(20),
 MAILCODE VARCHAR(5), CITY VARCHAR(20), COUNTRY VARCHAR(20))


INSERT INTO ADDRESS_COMMON(NAME, ADDRESS, MAILCODE, CITY, COUNTRY)
VALUES 
('RAJ','123',NULL,'HYDERABAD','INDIA'),
('RAM','234',NULL,'HYDERABAD','INDIA'),
('MIKE','999','1000','ARIZONA','USA'),
('DUKE','888','2000','DC','USA'),
('ROBERT','788','1000','MANCHESTER','UK'),
('ALIA','688','3000','LONDON','UK')


INSERT INTO ADDRESS_COMMON(NAME, ADDRESS, MAILCODE, CITY, COUNTRY)
VALUES
('JAMES','555','4000','NEW YORK','USA'),
('EMMA','101','5000','CHICAGO','USA'),
('LUCAS','202',NULL,'LOS ANGELES','USA'),
('OLIVIA','303','6000','SAN FRANCISCO','USA'),
('NOAH','404',NULL,'BOSTON','USA'),
('AVA','505','7000','MIAMI','USA'),
('LIAM','606','8000','TORONTO','CANADA'),
('SOPHIA','707','9000','VANCOUVER','CANADA'),
('MASON','808',NULL,'MONTREAL','CANADA'),
('ISABELLA','909','10000','OTTAWA','CANADA'),
('ETHAN','111','11000','SYDNEY','AUSTRALIA'),
('MIA','222','12000','MELBOURNE','AUSTRALIA'),
('LOGAN','333',NULL,'BRISBANE','AUSTRALIA'),
('CHARLOTTE','444','13000','PERTH','AUSTRALIA'),
('ELIJAH','555','14000','AUCKLAND','NEW ZEALAND'),
('AMELIA','666',NULL,'WELLINGTON','NEW ZEALAND'),
('HENRY','777','15000','DUBLIN','IRELAND'),
('EVELYN','888','16000','CORK','IRELAND'),
('JACK','999','17000','GLASGOW','SCOTLAND'),
('LILY','121','18000','EDINBURGH','SCOTLAND');

SELECT * FROM ADDRESS_COMMON where COUNTRY!='India'

select * from ADDRESS_INDIA
select * from ADDRESS_USA
select * from ADDRESS_OTHERS
select * from ADDRESS_INDIA
SELECT * FROM ADDRESS_COMMON

truncate table ADDRESS_INDIA
truncate table ADDRESS_USA
truncate table ADDRESS_OTHERS


SELECT * FROM ADDRESS_COMMON where COUNTRY='INDIA'
SELECT * FROM ADDRESS_COMMON where COUNTRY='USA'
SELECT * FROM ADDRESS_COMMON where COUNTRY NOT IN ('INDIA','USA')

NAME, ADDRESS, CITY, COUNTRY